### ISSUE TITLE
Feature Request: Blacklist

### ISSUE THREAD

**Issue by gorgarp** [Wolveix/Plexus#11]
Hey @Wolveix 
Can we get a blacklist function?

What I mean is, if a video won't encode, for things outside of Plexus' control, can we add it to a text file (manually, not requiring the software to do that).

Then, when calling "plexus list -d /path/to/things" we can put in something akin to an optional parameter of "-skip /path/to/textfile"

When scanning, assuming the file is in that text, it will drop it from the list.

Maybe something like: https://linux.die.net/man/1/fdupes

**Comment by Wolveix** [comment]
I can see how that could be useful, sounds good to me! I'll implement it soon :)

**Comment by gorgarp** [comment]
@Wolveix Awesome.

This will save me having to try / fail to encode the same over and over. Just added time :)

**Comment by Wolveix** [comment]
@Gorgarp Sorry this took so long. I've just implemented an experimental blacklist feature as well as macOS support with https://github.com/Wolveix/Plexus/commit/78ac2ddfd614b1fdaf0c9af3fe1af07422e9dfa2

Let me know how you get on with it!
