### ISSUE TITLE
Latest Commit Broke Ubuntu 19.04

### ISSUE THREAD

**Issue by gorgarp** [Wolveix/Plexus#12]
![2019-06-20 09_47_16-Window](https://user-images.githubusercontent.com/7957736/59858471-a364e800-9340-11e9-8481-7fdc8fc682d8.png)
![2019-06-20 09_47_44-root@plex-node_ ~](https://user-images.githubusercontent.com/7957736/59858473-a364e800-9340-11e9-94bf-43591029b2b0.png)

@Wolveix  Looks like uname output "Linux" on latest Ubuntu.

But awk -F= '/^NAME/{print $2}' /etc/os-release does output Ubuntu.

**Comment by gorgarp** [comment]
![2019-06-20 09_47_44-root@plex-node_ ~](https://user-images.githubusercontent.com/7957736/59858840-546b8280-9341-11e9-94dc-87ee3d19738c.png)
![2019-06-20 09_53_45-root@plex-node_ ~](https://user-images.githubusercontent.com/7957736/59858841-546b8280-9341-11e9-9264-64a6bc910d2f.png)

**Comment by Wolveix** [comment]
Ohhhhhh, I know what caused this. Thanks for catching that! I'll release a commit to fix this now.
