### ISSUE TITLE
Distro is not supported error

### ISSUE THREAD

**Issue by lavaswimmer** [Wolveix/Plexus#13]
**Describe the bug**
Getting the following error after using the auto installation script, so I used the manual installation. But after that still getting the same error when using any plexus command.

**Screenshots**
![Screenshot from 2019-07-14 14-41-55](https://user-images.githubusercontent.com/22656008/61183773-92f51400-a645-11e9-803a-bb85b11c312b.png)

**Desktop:**
 - OS: Pop Os 19.04
 - FFMPEG Version: 4.1.3-0ubuntu1
- Plexus v0.9.70r2

I hope this is enough information, this actually my first submitted issue :sweat_smile:

**Comment by gorgarp** [comment]
@lavaswimmer  Pop isn't really a supported distro. However, it's a downstream of Ubuntu.

What does this output? 

sudo awk -F= '/^NAME/{print $2}' /etc/os-release

Let's pretend it is "Popos" or whatever,

1. run "curl https://plexus.robt.me/install.sh"
2. nano/vim/vi whatever plexus.sh
3. Edit line 30 '"Linux Mint"' >> '"Popos"'
4. Write the file out
5. Run sudo bash ./install.sh

It should install, but fail when you run it. To fix, just edit the same line on /usr/bin/plexus.

@Wolveix I'm not certain how far down this road you want to go but we could add in a check if installer failed:

"Your distro is not supported but you can override this, if your distro is a variant of the ones below
1. Ubuntu
2. Redhat / Centos
3. Etc

No warranty of functionality is made if you choose to continue."

That way this scenario can continue if someone is running, xubuntu, fedora, yada yada yada.

**Comment by gorgarp** [comment]
@lavaswimmer Just a forewarning, if System76 did some "things" to locations of binaries, you'll need to map them out in the config 

sudo plexus config

**Comment by Wolveix** [comment]
@lavaswimmer Yeah, that would be because PopOS! isn't officially supported (though since it's basically a fork of Ubuntu, it should work just fine).

Thanks for the help @gorgarp! I'll add a catchall that asks the user whether they're using a variation of one of the supported distribution trees. Hopefully, I'll have time to do this tomorrow.

Thanks again!
