### ISSUE TITLE
FFmpeg Installer Broken on CentOS 8

### ISSUE THREAD

**Issue by gorgarp** [Wolveix/Plexus#16]
Installing any missing dependencies.
Error:
 Problem: package ffmpeg-devel-3.4.7-1.el7.x86_64 requires libavdevice.so.57()(64bit), but none of the providers can be installed
  - package ffmpeg-devel-3.4.7-1.el7.x86_64 requires libavdevice(x86-64) = 3.4.7-1.el7, but none of the providers can be installed
  - conflicting requests
  - nothing provides libcdio_cdda.so.1()(64bit) needed by libavdevice-3.4.7-1.el7.x86_64
  - nothing provides libcdio_cdda.so.1(CDIO_CDDA_1)(64bit) needed by libavdevice-3.4.7-1.el7.x86_64
  - nothing provides libcdio_paranoia.so.1()(64bit) needed by libavdevice-3.4.7-1.el7.x86_64
  - nothing provides libcdio_paranoia.so.1(CDIO_PARANOIA_1)(64bit) needed by libavdevice-3.4.7-1.el7.x86_64

Install completed!

**Comment by Wolveix** [comment]
Hey! Sorry for not seeing this sooner, I wasn't notified at all (and the holidays were pretty busy).

Looks like CentOS 8 changed a few things which broke our default dependency installer for FFmpeg. I'll do some testing and modify the installer script.

**Comment by craigusus** [comment]
Following as I get a similar issue on CentOS 8

```=== Plexus v0.9.72 - Developed by Robert Thomas ===
=== https://github.com/Wolveix/Plexus ===
Installing any missing dependencies...
Error:
 Problem 1: conflicting requests
  - nothing provides libSDL2-2.0.so.0()(64bit) needed by ffmpeg-3.4.7-3.el7.x86_                                                                                      64
 Problem 2: package ffmpeg-devel-3.4.7-3.el7.x86_64 requires libavdevice(x86-64)                                                                                       = 3.4.7-3.el7, but none of the providers can be installed
  - package ffmpeg-devel-3.4.7-3.el7.x86_64 requires libavdevice.so.57()(64bit),                                                                                       but none of the providers can be installed
  - conflicting requests
  - nothing provides libSDL2-2.0.so.0()(64bit) needed by libavdevice-3.4.7-3.el7                                                                                      .x86_64
  - nothing provides libcdio_cdda.so.1()(64bit) needed by libavdevice-3.4.7-3.el                                                                                      7.x86_64
  - nothing provides libcdio_cdda.so.1(CDIO_CDDA_1)(64bit) needed by libavdevice                                                                                      -3.4.7-3.el7.x86_64
  - nothing provides libcdio_paranoia.so.1()(64bit) needed by libavdevice-3.4.7-                                                                                      3.el7.x86_64
  - nothing provides libcdio_paranoia.so.1(CDIO_PARANOIA_1)(64bit) needed by lib                                                                                      avdevice-3.4.7-3.el7.x86_64

Install completed!

Please run 'plexus help' to see a list of available commands.```

**Comment by Wolveix** [comment]
@craigusus This will be addressed when Plexus v2 releases soon :) The error is caused by the dependency installer part of the installation. You can get around this issue by [manually installing FFmpeg on CentOS 8](https://linuxize.com/post/how-to-install-ffmpeg-on-centos-8/) and installing Plexus like this:

```shell
curl -O https://raw.githubusercontent.com/Wolveix/Plexus/master/plexus 2>/dev/null
chmod u+x plexus
mv plexus /usr/bin/plexus
```

**Comment by craigusus** [comment]
@Wolveix Thanks for the quick response. Tried the above and seems to be working well!
I did look at [#21](https://github.com/Wolveix/Plexus/issues/21) after I posted and saw you were still working on it. Thanks again!

**Comment by Wolveix** [comment]
@craigusus No worries! I'm glad that it's working for you. A lot of other work has come up recently which has sadly taken away from the time that I had hoped to use to focus on development of v2. Hopefully it won't be too much longer :)

**Comment by Wolveix** [comment]
Hey @gorgarp, mind giving this a test?

**Comment by gorgarp** [comment]
No worries, let me fire up a VM.

**Comment by gorgarp** [comment]
![image](https://user-images.githubusercontent.com/7957736/86524388-bf4e0580-be3f-11ea-8c16-3e5aff60df60.png)


No love.

So the problem could be fixed (tedious but...)

grep out centos version the add

Centos 8 == sudo dnf install --nogpgcheck https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
sudo dnf install --nogpgcheck https://download1.rpmfusion.org/free/el/rpmfusion-free-release-8.noarch.rpm https://download1.rpmfusion.org/nonfree/el/rpmfusion-nonfree-release-8.noarch.rpm && sudo dnf config-manager --enable PowerTools

Centos 7 == sudo yum localinstall --nogpgcheck https://download1.rpmfusion.org/free/el/rpmfusion-free-release-7.noarch.rpm https://download1.rpmfusion.org/nonfree/el/rpmfusion-nonfree-release-7.noarch.rpm

Or... we can trash RPM auto install and tell them to take their butts to RPMfusion ahead of time ;)

**Comment by gorgarp** [comment]
I'll keep the VM for a day or two. Just @ me if you want me to test something.

**Comment by Wolveix** [comment]
Haha, thanks for testing! It was a half-assed implementation. It's almost 04:00 here, so I'll spend some time sorting something decent out tomorrow :)

**Comment by gorgarp** [comment]
Lol yeah I was thinking that it's pretty late.

Could be worse, could be in the US where idiots refuse to believe COVID is real and kill us all *shrug*.

Thank god we are in IT and can hide in the basement :)

**Comment by Wolveix** [comment]
Haha, very true! You can get Cheetos over here, but they're not that popular. Wotsits on the other hand 👌

**Comment by Wolveix** [comment]
@craigusus @gorgarp The installer should now work on CentOS 8 :) I did some testing and it appears to be working as expected.
