### ISSUE TITLE
de-interlace input

### ISSUE THREAD

**Issue by samliddicott** [Wolveix/Plexus#17]
**Is your feature request related to a problem? Please describe.**
plex or (plex-player on chrome) can de-interlace the original mkv, but does not de-interlace the converted h264 mkv

**Describe the solution you'd like**
de-interlace while re-encoding

**Describe alternatives you've considered**
none

**Additional context**
adding: -vf yadif
as an ffmpeg option, via "$options" means that converted files play without interlace artifacts.

Maybe there are also bad side effects to this, but I don't know what they are. Maybe it should be based on the source file reporting as being interlaced.

**Comment by Wolveix** [comment]
Hey! Thanks for submitting the issue!

I'll have to do some research into it to ensure that it won't cause any adverse effects, but I'll add it to the to-do list and add a toggle to disable it just in case.

**Comment by Wolveix** [comment]
Implemented, thanks!
