### ISSUE TITLE
More efficient local media handling

### ISSUE THREAD

**Issue by samliddicott** [Wolveix/Plexus#18]
**Is your feature request related to a problem? Please describe.**
rsync of a 6GB source file before encoding starts is a waste of time, and slower and more wastier over an NFS share

**Describe the solution you'd like**
As the source file is natively accessible, as plexus doesn't intend to modify the source while encoding, could it avoid making a copy?

**Describe alternatives you've considered**
none

**Additional context**
while encoding, this allows encoding to start immediately without killing the network:
          #$rsync_binary -ah --info=progress2 "$line" "$convert_dir/$NAME/"
          mkdir -p "$convert_dir/$NAME/" && ln -sf "$line" "$convert_dir/$NAME/"

copying back isn't so bad as the file is 25% of size (thanks!)

**Comment by Wolveix** [comment]
Hey! Thanks for submitting the issue!

Due to varying flags, it makes sense to keep the behaviour as it is; however, I can fully appreciate where this would be useful. I'll add it to the to-do list, though it may be pushed for v2.0.0 rather than v1.0.0.

**Comment by Wolveix** [comment]
Actually, after reviewing things, I think symlinking should suffice. Copying was originally default due to Plexus being created with Rclone in mind, but you're absolutely right that this makes far more sense (of course copying back is still necessary). I'll prioritise getting this done!

**Comment by Wolveix** [comment]
Implemented, thanks!
