### ISSUE TITLE
plexus list doesn't ignore files with a [Plexus Encode] counterpart

### ISSUE THREAD

**Issue by samliddicott** [Wolveix/Plexus#19]
**Describe the bug**
If I encode a video without overwrite, such that a new copy is made with "[Plexus Encode]" in the file name, then a subsequent invocation of "plexus list" will re-select the same videos even though the conversion is there. There is no point in re-encoding.

**To Reproduce**
1. edit plexus.conf so that converted files are not overwritten: force_overwrite="false"
2. run plexus list -d /path/to/media
3. run plexus encode -l /path/to/list
see that a copy is produced with " [Plexus Encode]" added before the mkv extension
4. run plexus list -d /path/to/media
5 cat /path/to/list ; and see that the same file is listed to be converted again

**Expected behavior**
A non-compliant file that has a "[Plexus Encode]" counterpart doesn't need re-encoding -- at least not if force_overwrite="false"

**Setup:**
 - OS: Linux Mint 19.3 Tricia
 - FFMPEG Version: ffmpeg version 3.4.6-0ubuntu0.18.04.1
 - Script Version Ran: v0.9.70

**Additional context**

**Paste logs below this line**

**Comment by Wolveix** [comment]
Hey! Thanks for submitting the issue!

I couldn't agree more, I'll add this soon!

**Comment by Wolveix** [comment]
Implemented, thanks!
