### ISSUE TITLE
Add Fedora Support

### ISSUE THREAD

**Issue by gorgarp** [Wolveix/Plexus#20]
release for awk statment = 'Fedora"

add rpmfusion (similar to epel on centos:

sudo dnf install https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm

sudo dnf install  https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm

same dependencies as centos (ffmpeg, ffmpeg-devel) rsync installed by default though, so ignore it.

Otherwise should work out of the box.

**Comment by Wolveix** [comment]
Only just saw this after seeing your fork :P Sure thing, I'll get on this.

**Comment by Wolveix** [comment]
Implemented, please test it out and let me know if there are any issues! I don't have a Fedora install to play around with right now, unfortunately.

**Comment by gorgarp** [comment]
No worries. I'm happy to test. Puking saying not supported, which is odd. I'm guessing it's related to what it's seeing in /etc/os-release. Output here for your review.

[root@localhost ~]# awk -F= '/^NAME/{print $2}' /etc/os-release
Fedora


[root@localhost ~]# cat /etc/os-release
NAME=Fedora
VERSION="32 (Server Edition)"
ID=fedora
VERSION_ID=32
VERSION_CODENAME=""
PLATFORM_ID="platform:f32"
PRETTY_NAME="Fedora 32 (Server Edition)"
ANSI_COLOR="0;34"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:32"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f32/system-administrators-guide/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=32
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=32
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Server Edition"
VARIANT_ID=server
[root@localhost ~]#

**Comment by Wolveix** [comment]
Ah, I know why. One sec :)

**Comment by gorgarp** [comment]
haha sounds good. Working from home now-a-days so I'll be around :-p

**Comment by Wolveix** [comment]
My job is 99% from home anyway, so same old for me :P I've just pushed a potential fix, give it a try and let me know!

**Comment by gorgarp** [comment]
[root@localhost ~]# curl https://plexus.robt.me/install.sh | sudo bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3264    0  3264    0     0   6620      0 --:--:-- --:--:-- --:--:--  6607
=== Plexus v0.9.72 - Developed by Robert Thomas ===
=== https://github.com/Wolveix/Plexus ===
Installing any missing dependencies...

Install completed!

Please run 'plexus help' to see a list of available commands.



Working beautifully! Thanks bud :)
