### ISSUE TITLE
Dockerized Plexus

### ISSUE THREAD

**Issue by p4xel** [Wolveix/Plexus#21]
It would be great if there was an option to run the app a a Docker container.
Just a thought. If this is too much work, I will try to compose one myself.
Great job by the way!

**Comment by Wolveix** [comment]
Hey! Thank you for using Plexus :) I'm actually in the middle of rewriting the entirety of Plexus in Golang, which will include a Dockerfile. It should be released very soon with a load of new features! Speaking of, if you happen to have any feature requests, feel free to post them here!

**Comment by p4xel** [comment]
Two features, which should not be hard to implement: maximum bitrate for output streams and scheduled scan for new videos. Great seeing you keep working on the project. Keep it up and stay safe.

**Comment by Wolveix** [comment]
Those are both already being worked on, but it's great to see that they're wanted! 

Thanks, you too :)

**Comment by onezero1010101** [comment]
@Wolveix Any update on Release v2 and the Docker?  Do you mind if I work on building this into a Docker in the mean time?

**Comment by Wolveix** [comment]
@onezero1010101 Apologies, I've unfortunately been incredibly busy. I can push out a Docker image for v1 in the next couple of days :)

**Comment by Wolveix** [comment]
@p4xel @onezero1010101 v1 now has Docker support, v2 will have it on release :) The image is available via Docker Hub (wolveix/plexus:latest) or via Docker Packages (docker.pkg.github.com/Wolveix/Plexus/Plexus:latest).
