### ISSUE TITLE
Unable to find a suitable output format

### ISSUE THREAD

**Issue by Beariful** [Wolveix/Plexus#22]
**Describe the bug**
Unable to find a suitable output format for '' 

**To Reproduce**
1. Installed script (did not change default config)
2. Ran script on a movie file (same container type (mkv), different audio & video codex)
3. Ran script on a movie file (different container type (mp4 -> mkv), same audio (aac -> aac) & video codex(h264 -> h264))

**Expected behavior**
I expected two of these files to be converted.

**Setup:**
 - OS: Debian 10.4
 - FFMPEG Version: 4.2.2
 - Script Version Ran: 0.9.75

**Additional context**
I did some research, it seemed like this was related to not specifying a codex for ffmpeg to output to, so I tried to use the -a & -v with plexus encode, but that produced the same result. I checked the plexus conf file to make sure those two were set, and they both were. I was also confused by the lines like "--pkgconfigdir=/root/ffmpeg-build/workspace/lib/pkgconfig" because during the install steps it removes "/root/ffmpeg-build/" in the last step, which is unrelated but confused me while I was trying to troubleshot this.

**Paste logs below this line**
plex@hostname:~$ plexus encode --verbose
=== Plexus v0.9.75 - https://github.com/Wolveix/Plexus ===

Audio codec: aac
List file: /home/plex/.plexus/list.txt
Media container: mkv
Media directory: /mnt/plexdrive
Mount Path:
Video codec: h264

Copying: Star Wars The Rise of Skywalker (2019).mkv

File copied.

File codecs:
Audio = ac3 -> aac
Container = mkv -> mkv
Video = hevc -> h264

ffmpeg version 4.2.2-d1e8be3 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 8 (Debian 8.3.0-6)
  configuration: --pkgconfigdir=/root/ffmpeg-build/workspace/lib/pkgconfig --prefix=/root/ffmpeg-build/workspace --pkg-config-flags=--static --extra-cflags=-I/root/ffmpeg-build/workspace/include --extra-ldflags=-L/root/ffmpeg-build/workspace/lib --extra-libs='-lpthread -lm' --enable-static --disable-debug --disable-shared --disable-ffplay --disable-doc --enable-openssl --enable-gpl --enable-version3 --enable-nonfree --enable-pthreads --enable-libvpx --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libx264 --enable-libx265 --enable-runtime-cpudetect --enable-libfdk-aac --enable-avfilter --enable-libopencore_amrwb --enable-libopencore_amrnb --enable-filters --enable-libvidstab --enable-libaom
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
Input #0, matroska,webm, from '/home/plex/.plexus/encode/convert/Star Wars The Rise of Skywalker (2019)/Star Wars The Rise of Skywalker (2019).mkv':
  Metadata:
    title           : Star Wars: Episode IX - The Rise of Skywalker 2019 from селезень
    encoder         : libebml v1.3.9 + libmatroska v1.5.2
    creation_time   : 2020-03-20T13:59:01.000000Z
  Duration: 02:21:53.28, start: 0.000000, bitrate: 53090 kb/s
    Chapter #0:0: start 0.000000, end 9.176000
    Metadata:
      title           : Opening Logo
    Chapter #0:1: start 9.176000, end 100.934000
    Metadata:
      title           : The Rise Of Skywalker
    Chapter #0:2: start 100.934000, end 227.811000
    Metadata:
      title           : Kylo Ren's Quest
    Chapter #0:3: start 227.811000, end 402.902000
    Metadata:
      title           : Exegol
    Chapter #0:4: start 402.902000, end 506.673000
    Metadata:
      title           : Millenium Falcon Mission
    Chapter #0:5: start 506.673000, end 604.896000
    Metadata:
      title           : Pursuit Of The Falcon
    Chapter #0:6: start 604.896000, end 768.142000
    Metadata:
      title           : Rey's Training Course
    Chapter #0:7: start 768.142000, end 834.000000
    Metadata:
      title           : General Leia
    Chapter #0:8: start 834.000000, end 917.416000
    Metadata:
      title           : The Falcon's Back
    Chapter #0:9: start 917.416000, end 1033.199000
    Metadata:
      title           : Spy Message
    Chapter #0:10: start 1033.199000, end 1165.039000
    Metadata:
      title           : "We Go Together"
    Chapter #0:11: start 1165.039000, end 1288.579000
    Metadata:
      title           : Ren Reforged
    Chapter #0:12: start 1288.579000, end 1527.693000
    Metadata:
      title           : Pasaana Festival
    Chapter #0:13: start 1527.693000, end 1634.883000
    Metadata:
      title           : General Calrissian
    Chapter #0:14: start 1634.883000, end 1841.548000
    Metadata:
      title           : Speeder Chase
    Chapter #0:15: start 1841.548000, end 2149.064000
    Metadata:
      title           : Buried Secrets
    Chapter #0:16: start 2149.064000, end 2497.745000
    Metadata:
      title           : Power Unleashed
    Chapter #0:17: start 2497.745000, end 2595.259000
    Metadata:
      title           : Aftermath
    Chapter #0:18: start 2595.259000, end 2728.351000
    Metadata:
      title           : "In This Till The End"
    Chapter #0:19: start 2728.351000, end 2904.568000
    Metadata:
      title           : Meeting Zorii
    Chapter #0:20: start 2904.568000, end 3277.566000
    Metadata:
      title           : Babu Firk's Workshop
    Chapter #0:21: start 3277.566000, end 3529.192000
    Metadata:
      title           : Into The Destroyer
    Chapter #0:22: start 3529.192000, end 3774.771000
    Metadata:
      title           : Revelations
    Chapter #0:23: start 3774.771000, end 3983.104000
    Metadata:
      title           : Repercussions
    Chapter #0:24: start 3983.104000, end 4194.607000
    Metadata:
      title           : To Kef Bir
    Chapter #0:25: start 4194.607000, end 4387.383000
    Metadata:
      title           : Jannah
    Chapter #0:26: start 4387.383000, end 4703.616000
    Metadata:
      title           : The Emperor's Vault
    Chapter #0:27: start 4703.616000, end 5021.225000
    Metadata:
      title           : The Duel
    Chapter #0:28: start 5021.225000, end 5222.884000
    Metadata:
      title           : Remembrance
    Chapter #0:29: start 5222.884000, end 5423.126000
    Metadata:
      title           : The Final Order Begins
    Chapter #0:30: start 5423.126000, end 5700.820000
    Metadata:
      title           : The Destiny Of A Jedi
    Chapter #0:31: start 5700.820000, end 5927.880000
    Metadata:
      title           : Battle Plans
    Chapter #0:32: start 5927.880000, end 6035.863000
    Metadata:
      title           : Welcome To Exegol
    Chapter #0:33: start 6035.863000, end 6183.135000
    Metadata:
      title           : Drop Zone
    Chapter #0:34: start 6183.135000, end 6327.863000
    Metadata:
      title           : Throne Of The Sith
    Chapter #0:35: start 6327.863000, end 6528.188000
    Metadata:
      title           : Dark Turn
    Chapter #0:36: start 6528.188000, end 6807.634000
    Metadata:
      title           : Dyad In The Force
    Chapter #0:37: start 6807.634000, end 6930.757000
    Metadata:
      title           : The Galaxy Responds
    Chapter #0:38: start 6930.757000, end 7142.969000
    Metadata:
      title           : Emperor Reborn
    Chapter #0:39: start 7142.969000, end 7297.749000
    Metadata:
      title           : Last Chance
    Chapter #0:40: start 7297.749000, end 7520.430000
    Metadata:
      title           : Ben
    Chapter #0:41: start 7520.430000, end 7782.692000
    Metadata:
      title           : Victory
    Chapter #0:42: start 7782.692000, end 7945.896000
    Metadata:
      title           : Saga's End
    Chapter #0:43: start 7945.896000, end 8513.280000
    Metadata:
      title           : End Credits
    Stream #0:0(eng): Video: hevc (Main 10), yuv420p10le(tv, bt2020nc/bt2020/smpte2084), 3840x2160 [SAR 1:1 DAR 16:9], 23.98 fps, 23.98 tbr, 1k tbn, 23.98 tbc (default)
    Metadata:
      BPS-eng         : 46106382
      DURATION-eng    : 02:21:53.255000000
      NUMBER_OF_FRAMES-eng: 204114
      NUMBER_OF_BYTES-eng: 49064423878
      _STATISTICS_WRITING_APP-eng: mkvmerge v40.0.0 ('Old Town Road + Pony') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2020-03-20 13:59:01
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:1(rus): Audio: ac3, 48000 Hz, 5.1(side), fltp, 384 kb/s (default) (forced)
    Metadata:
      title           : iTunes
      BPS-eng         : 384000
      DURATION-eng    : 02:21:52.416000000
      NUMBER_OF_FRAMES-eng: 266013
      NUMBER_OF_BYTES-eng: 408595968
      _STATISTICS_WRITING_APP-eng: mkvmerge v40.0.0 ('Old Town Road + Pony') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2020-03-20 13:59:01
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:2(eng): Audio: truehd, 48000 Hz, 7.1, s32 (24 bit)
    Metadata:
      title           : Original
      BPS-eng         : 5890175
      DURATION-eng    : 02:21:53.256000000
      NUMBER_OF_FRAMES-eng: 10215907
      NUMBER_OF_BYTES-eng: 6268071650
      _STATISTICS_WRITING_APP-eng: mkvmerge v40.0.0 ('Old Town Road + Pony') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2020-03-20 13:59:01
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:3(eng): Audio: ac3, 48000 Hz, 5.1(side), fltp, 640 kb/s
    Metadata:
      BPS-eng         : 640000
      DURATION-eng    : 02:21:53.280000000
      NUMBER_OF_FRAMES-eng: 266040
      NUMBER_OF_BYTES-eng: 681062400
      _STATISTICS_WRITING_APP-eng: mkvmerge v40.0.0 ('Old Town Road + Pony') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2020-03-20 13:59:01
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:4(rus): Subtitle: subrip (default) (forced)
    Metadata:
      title           : Forced
      BPS-eng         : 1
      DURATION-eng    : 01:37:13.934000000
      NUMBER_OF_FRAMES-eng: 10
      NUMBER_OF_BYTES-eng: 938
      _STATISTICS_WRITING_APP-eng: mkvmerge v40.0.0 ('Old Town Road + Pony') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2020-03-20 13:59:01
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:5(rus): Subtitle: subrip
    Metadata:
      title           : Full
      BPS-eng         : 57
      DURATION-eng    : 02:17:27.122000000
      NUMBER_OF_FRAMES-eng: 1435
      NUMBER_OF_BYTES-eng: 59535
      _STATISTICS_WRITING_APP-eng: mkvmerge v40.0.0 ('Old Town Road + Pony') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2020-03-20 13:59:01
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:6(rus): Subtitle: subrip
    Metadata:
      title           : SDH
      BPS-eng         : 73
      DURATION-eng    : 02:11:46.991000000
      NUMBER_OF_FRAMES-eng: 1764
      NUMBER_OF_BYTES-eng: 72830
      _STATISTICS_WRITING_APP-eng: mkvmerge v40.0.0 ('Old Town Road + Pony') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2020-03-20 13:59:01
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:7(eng): Subtitle: subrip
    Metadata:
      title           : Full
      BPS-eng         : 39
      DURATION-eng    : 02:11:57.460000000
      NUMBER_OF_FRAMES-eng: 1460
      NUMBER_OF_BYTES-eng: 38759
      _STATISTICS_WRITING_APP-eng: mkvmerge v40.0.0 ('Old Town Road + Pony') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2020-03-20 13:59:01
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:8(eng): Subtitle: subrip
    Metadata:
      title           : SDH
      BPS-eng         : 48
      DURATION-eng    : 02:11:50.035000000
      NUMBER_OF_FRAMES-eng: 1895
      NUMBER_OF_BYTES-eng: 48192
      _STATISTICS_WRITING_APP-eng: mkvmerge v40.0.0 ('Old Town Road + Pony') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2020-03-20 13:59:01
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
[NULL @ 0x557ca9919740] Unable to find a suitable output format for ''
: Invalid argument

An unknown error occurred with FFmpeg.

Error: /home/plex/movies/starwars/Star Wars The Rise of Skywalker (2019).mkv could not be encoded.

Moving onto the next line.

Copying: Uncut Gems (2019).mp4

File copied.

File codecs:
Audio = aac -> libfdk_aac
Container = mp4 -> mkv
Video = h264 -> h264

ffmpeg version 4.2.2-d1e8be3 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 8 (Debian 8.3.0-6)
  configuration: --pkgconfigdir=/root/ffmpeg-build/workspace/lib/pkgconfig --prefix=/root/ffmpeg-build/workspace --pkg-config-flags=--static --extra-cflags=-I/root/ffmpeg-build/workspace/include --extra-ldflags=-L/root/ffmpeg-build/workspace/lib --extra-libs='-lpthread -lm' --enable-static --disable-debug --disable-shared --disable-ffplay --disable-doc --enable-openssl --enable-gpl --enable-version3 --enable-nonfree --enable-pthreads --enable-libvpx --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libx264 --enable-libx265 --enable-runtime-cpudetect --enable-libfdk-aac --enable-avfilter --enable-libopencore_amrwb --enable-libopencore_amrnb --enable-filters --enable-libvidstab --enable-libaom
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/home/plex/.plexus/encode/convert/Uncut Gems (2019)/Uncut Gems (2019).mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.35.100
  Duration: 02:15:00.08, start: 0.000000, bitrate: 2239 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1920x800 [SAR 1:1 DAR 12:5], 2099 kb/s, 24 fps, 24 tbr, 12288 tbn, 48 tbc (default)
    Metadata:
      handler_name    : VideoHandler
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 134 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
[NULL @ 0x55b3df8d2480] Unable to find a suitable output format for ''
: Invalid argument

An unknown error occurred with FFmpeg.
Trying with full conversion instead.

ffmpeg version 4.2.2-d1e8be3 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 8 (Debian 8.3.0-6)
  configuration: --pkgconfigdir=/root/ffmpeg-build/workspace/lib/pkgconfig --prefix=/root/ffmpeg-build/workspace --pkg-config-flags=--static --extra-cflags=-I/root/ffmpeg-build/workspace/include --extra-ldflags=-L/root/ffmpeg-build/workspace/lib --extra-libs='-lpthread -lm' --enable-static --disable-debug --disable-shared --disable-ffplay --disable-doc --enable-openssl --enable-gpl --enable-version3 --enable-nonfree --enable-pthreads --enable-libvpx --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libx264 --enable-libx265 --enable-runtime-cpudetect --enable-libfdk-aac --enable-avfilter --enable-libopencore_amrwb --enable-libopencore_amrnb --enable-filters --enable-libvidstab --enable-libaom
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/home/plex/.plexus/encode/convert/Uncut Gems (2019)/Uncut Gems (2019).mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.35.100
  Duration: 02:15:00.08, start: 0.000000, bitrate: 2239 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1920x800 [SAR 1:1 DAR 12:5], 2099 kb/s, 24 fps, 24 tbr, 12288 tbn, 48 tbc (default)
    Metadata:
      handler_name    : VideoHandler
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 134 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
[NULL @ 0x56455d73e480] Unable to find a suitable output format for ''
: Invalid argument

An unknown error occurred with FFmpeg.

Error: /home/plex/movies/uncutgems/Uncut Gems (2019).mp4 could not be encoded.

Moving onto the next line.

**My config file in case you need it**
audio_codec="aac"
blacklist_file="$HOME/.plexus/blacklist"
convert_dir="$HOME/.plexus/encode/convert"
converted_dir="$HOME/.plexus/encode/converted"
deinterlacing="true"
ffmpeg_binary="/usr/bin/ffmpeg"
ffmpeg_threads="2"
ffmpeg_preset="faster"
ffprobe_binary="/usr/bin/ffprobe"
force_overwrite="true"
fusermount_binary="/usr/bin/fusermount"
hardware_acceleration="false"
hardware_codec="opencl"
list_file="$HOME/.plexus/list.txt"
media_container="mkv"
media_dir="/mnt/plexdrive"
mount_dir=""
rclone_binary="/usr/bin/rclone"
rsync_binary="/usr/bin/rsync"
video_codec="h264"
video_library="libx264"

**Comment by shakoin** [comment]
I was able to get plexus to work by downgrading to the V0.9.72.
Assuming there might be an issue with one changes from the script after that point more than likely with how argument are being passed.

**Comment by Wolveix** [comment]
That's certainly possible. The latest revisions have primarily been cleanups, so there's a chance that it wasn't tested properly. I've been heavily prioritizing the release of v2 as it'll have built-in unit tests, helping to prevent this from occurring in the future. 

I'll review the code and potentially rollback to v0.9.72. Thanks @Bearful and @shakoin.

**Comment by Wolveix** [comment]
The repo has been rolled back to v0.9.72. This issue should be resolved.
