### ISSUE TITLE
Force Encode Audio, Copy Video Regardless

### ISSUE THREAD

**Issue by gorgarp** [wolveix/plexus#25]
Hey bud. When you get a sec, even if it's in the GO version, can you add an option to ignore variable ($video_format or whatever) for video encode, only copy video (-copy) and encode only audio?

Use case, video is great but lossless audio is adding +500MB per file. 

Don't know about you but my ears can't tell the difference ;)

**Comment by Wolveix** [comment]
Hey! So you want an option to copy the video and force encode the audio? 

Yeah, I care about audio quality, but it's hard to tell with movies/TV haha.

**Comment by gorgarp** [comment]
Haha well said. Yes, please, if we could at some point. It would allow roughly a 10% saving is overall space, without the work of re-encoding the video on 5k files ;-P

**Comment by Wolveix** [comment]
Sweet, I'll get it done! I might sort it for v1, but it's more likely that it'll be pushed to v2. I was hoping that I would have v2 ready a month ago, but life's been busy as heck. It'll be worth it though 😎
