### ISSUE TITLE
Arch support in install.sh

### ISSUE THREAD

**Issue by igoro00** [Wolveix/Plexus#26]
Your install script doesnt support Arch(also its not in this repo so i cant really add it for you) and its derivatives.

You can add something like this inside `case $distro in`
`'"Manjaro Linux"' | '"Arch Linux"' | '"ArcoLinuxD"')
        printf "\\n\\e[36mInstalling any missing dependencies...\\n\\e[94m"
        pacman -Syu
        pacman -S curl ffmpeg rsync
        ;;`

I didn't test the install for Arco Linux but I'm pretty sure it's gonna work fiiiinneee... xd

**Comment by Wolveix** [comment]
Hey :) All files relative to this project are in this repo, you can find the installer script at `docs/install.sh`.

Feel free to submit a PR with those changes, or I can makethem myself.

Thanks!

**Comment by igoro00** [comment]
oh, that location is a bit confusing :) I can submit PR rn

**Comment by Wolveix** [comment]
Sweet, I'll review it once you've submitted it. `docs` is a standard location for GitHub Pages.

**Comment by Wolveix** [comment]
Merged, thanks!
