### ISSUE TITLE
hardware acceleration for encoding

### ISSUE THREAD

**Issue by hwaccel** [Wolveix/Plexus#3]
**Is your feature request related to a problem? Please describe.**
Slow encoding of files and not using the gpu to encode.

**Describe the solution you'd like**
On line 603ish, I think, is when the command to do the actual conversion is, if you add the option '-hwaccel opencl' it will allow ffmpeg to us the opencl hardware acceleration it isn't the fastest but it works on every type of gpu make.

**Describe alternatives you've considered**

**Additional context**
The api's available for ffmpeg and the compatibility chart.
https://trac.ffmpeg.org/wiki/HWAccelIntro

**Comment by Wolveix** [comment]
Experimental hardware acceleration support has been added in [Plexus v0.9.64](https://github.com/Wolveix/Plexus/commit/8d866d44f9a1c8b3eda9fe6be08306d2303f46ff) :) 

Thanks for the feature request!
