### ISSUE TITLE
The Docker Image Keeps Restarting

### ISSUE THREAD

**Issue by Emmer123** [Wolveix/Plexus#34]
Hi sorry to be a bother, but i can't seem to find any documentation on how to use the docker image besides installing it. 
I did just what the readme describes but the docker just keeps restarting doing the plexus command. I figured it might be trying to do something automatic so i changed the config file and put a sample list for it to go do its thing. However that's not the case. And because it just keeps restarting i'm unable to connect into it to see what it's doing 

The log file just keeps spitting the following over and over and over 

```
=== Plexus v0.9.74 - https://github.com/Wolveix/Plexus ===



Usage:
  plexus [flags]

  plexus [command]

Available Commands:
  about           Learn more about the program
  blacklist       Add an entry to the blacklist
  config          Change the default variable values
  encode          Begin processing the encode queue
  help            Displays a list of available commands
  install         Reinstall Plexus or install any missing dependencies
  list            Build a .txt file containing media with incorrect codecs
  mount           Mount an Rclone remote or cache, set from the config function
  unmount         Unmount an Rclone remote or cache, set from the config function

Additional Information:
  Use 'plexus help command' to find out more about a specific command
```

**To Reproduce**
1. install the docker like the readme.md describes
2. Start the docker
3. looping behavior as described

**Expected behavior**
I expected to be able to remote into the docker to have it encode all my media according to the list.txt and not have to worry about dependencies like the readme describes :)

**Screenshots**
n/a

**Setup:**
 - OS: Centos
 - Docker FFMPEG Version:alpine something i think according to dockerfile (however not relevant in this case it doesn't get that far
 - Script Version Ran: 0.9.74

**Comment by Wolveix** [comment]
Hi there! Thanks for taking the time to open this issue.

Plexus does not run as a service, so you need to provide a command to it for it to run. For example, if you want to run the `list` function, you would run the container like this:

```
​docker run -v ​$HOME​/.config/plexus:/root/.config/plexus -v ​$HOME​/.plexus:/root/.plexus -v /path/to/media:/media wolveix/Plexus:latest list
```

I'll add some additional documentation to reflect this :)

**Comment by Emmer123** [comment]
Ah i see ok that makes sense, thank you very much indeed i'll give that a go. 
And thank you very much for the incredibly fast reply. 

One last thing, what would you recommend as a place of support for plexus? I see there is a very busy thread on the rclone forums, is that the right place?

**Comment by Wolveix** [comment]
You're welcome! Currently GitHub us the only official place for support, but I would be happy to open a dedicated forum if there was interest!
