### ISSUE TITLE
Cleanup

### ISSUE THREAD

**Issue by gorgarp** [Wolveix/Plexus#5]
**Describe the solution you'd like**
Add prompt at beginning of encode function:

Clean existing conversion cache? y/n

If yes, clean .plexus/convert & converted folders

**Describe alternatives you've considered**
Manual cleaning

**Additional context**
Basically, if you halt the script mid run, it leaves crap behind, which can fill up drives.

**Comment by Wolveix** [comment]
Thanks for the suggestion! Automated file cleanup was supposed to be implemented a long time ago, clearly I forgot about it. I haven't added a prompt as I don't believe there's any major benefit to keeping the file cache in any scenario, so the cache is automatically cleared upon each loop. This has been implemented in [Plexus v0.9.65](https://github.com/Wolveix/Plexus/commit/7e6c37c8e62fa336480a20af481054a21c39f0f0).
