### ISSUE TITLE
Failed Conversion Leaves Artifacts

### ISSUE THREAD

**Issue by gorgarp** [Wolveix/Plexus#6]
**Describe the bug**
If conversion fails both attempts, it moves on to the next line, which is good.

However, it leaves the copied file in the convert directory, which is bad ;)

**Comment by Wolveix** [comment]
Thanks for the suggestion! This goes with issue #5. This was supposed to be implemented a long time ago, clearly I forgot about it. The cache is now automatically cleared when this happens. This has been implemented in [Plexus v0.9.66](https://github.com/Wolveix/Plexus/commit/36c389dc26d331b1a3bdd2d7f770b733436859ae).
