### ISSUE TITLE
HWaccel erorr

### ISSUE THREAD

**Issue by gorgarp** [Wolveix/Plexus#7]
Breaks when trying to use opencl:

ffmpeg version 4.1 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.3.0-27ubuntu1~18.04)
  configuration: --pkgconfigdir=/home/user/ffmpeg-build/workspace/lib/pkgconfig --prefix=/home/user/ffmpeg-build/workspace --pkg-config-flags=--static --extra-cflags=-I/home/user/ffmpeg-build/workspace/include --extra-ldflags=-L/home/user/ffmpeg-build/workspace/lib --extra-libs='-lpthread -lm' --enable-static --disable-debug --disable-shared --disable-ffplay --disable-doc --enable-gpl --enable-version3 --enable-nonfree --enable-pthreads --enable-libvpx --enable-libmp3lame --enable-libtheora --enable-libvorbis --enable-libx264 --enable-libx265 --enable-runtime-cpudetect --enable-libfdk-aac --enable-avfilter --enable-libopencore_amrwb --enable-libopencore_amrnb --enable-filters --enable-libvidstab --enable-libaom
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/home/user/.plexus/encode/convert/movie.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf57.48.101
  Duration: 02:16:10.97, start: 0.000000, bitrate: 1017 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1280x544 [SAR 1:1 DAR 40:17], 899 kb/s, 23.98 fps, 23.98 tbr, 24k tbn, 47.95 tbc (default)
    Metadata:
      handler_name    : VideoHandler
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 110 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
Option hwaccel (use HW accelerated decoding) cannot be applied to output url /home/user/.plexus/encode/converted/movie.mkv -- you are trying to apply an input option to an output file or vice versa. Move this option before the file it belongs to.
Error parsing options for output file /home/user/.plexus/encode/converted/movie.mkv.
Error opening output files: Invalid argument

An unknown error occurred with FFmpeg.
Trying with full conversion instead.

ffmpeg version 4.1 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.3.0-27ubuntu1~18.04)
  configuration: --pkgconfigdir=/home/user/ffmpeg-build/workspace/lib/pkgconfig --prefix=/home/user/ffmpeg-build/workspace --pkg-config-flags=--static --extra-cflags=-I/home/user/ffmpeg-build/workspace/include --extra-ldflags=-L/home/user/ffmpeg-build/workspace/lib --extra-libs='-lpthread -lm' --enable-static --disable-debug --disable-shared --disable-ffplay --disable-doc --enable-gpl --enable-version3 --enable-nonfree --enable-pthreads --enable-libvpx --enable-libmp3lame --enable-libtheora --enable-libvorbis --enable-libx264 --enable-libx265 --enable-runtime-cpudetect --enable-libfdk-aac --enable-avfilter --enable-libopencore_amrwb --enable-libopencore_amrnb --enable-filters --enable-libvidstab --enable-libaom
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/home/user/.plexus/encode/convert/movie.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf57.48.101
  Duration: 02:16:10.97, start: 0.000000, bitrate: 1017 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1280x544 [SAR 1:1 DAR 40:17], 899 kb/s, 23.98 fps, 23.98 tbr, 24k tbn, 47.95 tbc (default)
    Metadata:
      handler_name    : VideoHandler
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 110 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
Option hwaccel (use HW accelerated decoding) cannot be applied to output url /home/user/.plexus/encode/converted/movie].mkv -- you are trying to apply an input option to an output file or vice versa. Move this option before the file it belongs to.
Error parsing options for output file /home/user/.plexus/encode/converted/movie.mkv.
Error opening output files: Invalid argument

An unknown error occurred with FFmpeg.

Error: /media/Data/Movies/movie.mp4 could not be encoded.

Moving onto the next line.

**Comment by Wolveix** [comment]
Looks like the -hwaccel flag within FFmpeg has to be set before the input file is declared. Thanks for testing it out! This has been fixed in [Plexus v0.9.67](https://github.com/Wolveix/Plexus/commit/28d192e137f7806a7366a3a68b7748573ac232ae).
