### ISSUE TITLE
Plex versions folder

### ISSUE THREAD

**Issue by benderstwin** [Wolveix/Plexus#9]
This looks like exactly what I need.  Is there a way to place the encoded file into a folder that plex would pick up as another version?  I think it needs to be in the same directory, in  "plex versions" folder with the same filename, and the quality in ().

**Comment by Wolveix** [comment]
Hey! Sorry for taking so long to reply to this, I've been incredibly busy with work. While this is certainly doable, the requirement of including the quality would be a pain. I could obtain the video height and width, but there are so many different possibilities to allow for. Then you also have to consider the margin for error (for example, a "1080p" video possessing the resolution of 1918 x 1078 wouldn't be picked up as 1080p and would instead fail).

As Plexus doesn't resize videos, I'm not sure what benefit this feature might add to the script. The quality would still be the same as the source file, so you're best off either allowing Plexus to simply overwrite the original file, or disable the `force_overwright` configuration flag which will then include `[Plexus Encode]` at the end of the filename.
